name: Update README with Icons

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set executable permission for script
      run: chmod +x ./.github/readme-format.sh

    - name: Run readme format script
      run: ./.github/readme-format.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update README icons'
        title: 'Update README with Icons'
        body: |
          Updating the README with the latest icons table.
        labels: 'automated'
